# Site settings
title: "Tutorial: Risk Modeling with Probabilistic Programs"
author: "Russell Cameron Thomas"
author_title: "PhD Candidate"
author_dept: "Computational & Data Sciences"
author_affiliation: "George Mason University"
baseurl: ""
#baseurl: "http://riskmodels.meritology.com"
url: "http://riskmodels.meritology.com"

# Build settings
markdown: kramdown

exclude:
- node_modules