# Site settings
title: "Library"
collections:
  posts:
    output: false
    sort_order: -1
    index: false
    title: "Meritology Blog"
  fundamentals:
    output: true
    sort_order: 0
    index : true
    title: "Tutorial: Fundamentals of Probabilistic Programming"
  riskmodels:
    output: true
    sort_order: 1
    index : true
    title: "Tutorial: Risk Modeling with Probabilistic Programming"
  financial:
    output: true
    sort_order: 2
    index : true
    title: "Tutorial: Financial Applications of Probabilistic Programming"
  institutions:
    output: true
    sort_order: 3
    index : true
    title: "Models of Teams, Institutions, and Innovation"
  incentives:
    output: true
    sort_order: 4
    index : true
    title: "Models of Intrinsic and Extrinsic Incentives"
  cyberinsurance:
    output: true
    sort_order: 5
    index : true
    title: "Models of Cyber Insurance"
  ecosystems:
    output: true
    sort_order: 6
    index : true
    title: "A Theory of Functional Ecosystems"
  info:
    output: true
    sort_order: 10
    index : false
    title: "Site Information"
author: "Russell Cameron Thomas"
author_title: "PhD Candidate"
author_dept: "Computational & Data Sciences"
author_affiliation: "George Mason University"
author_url: "/info/chapters/0_team.html"
baseurl: ""
url: "http://library.meritology.com"

# Put blob posts in their own directory
permalink: /blog/:year/:month/:title.html

# Build settings
markdown: kramdown

exclude:
- node_modules