# Site settings
title: Modeling Agents with Probabilistic Programs
baseurl: "/riskmodels"
url: "http://russellcameronthomas.github.io/riskmodels"

# Build settings
markdown: kramdown

exclude:
- node_modules