# Site settings
title: Risk Modeling with Probabilistic Programs
baseurl: ""
#baseurl: "http://riskmodels.meritology.com"
url: "http://riskmodels.meritology.com"

# Build settings
markdown: kramdown

exclude:
- node_modules