# Site settings
title: "Library"
collections:
  riskmodels:
    output: true
    sort_order: 0
    title: "Tutorial: Risk Modeling with Probabilistic Programming"
  institutions:
    output: true
    sort_order: 1
    title: "Models of Teams, Institutions, and Innovation"

tutorial_title_1: "Risk Modeling with Probabilistic Programming"
tutorial_title_2: "Teams, Institutions, and Innovation"
tutorial_title_3: ""
tutorial_title_4: ""
tutorial_directory_1: "riskmodels"
tutorial_directory_2: "institutions"
tutorial_directory_3: ""
tutorial_directory_4: ""
author: "Russell Cameron Thomas"
author_title: "PhD Candidate"
author_dept: "Computational & Data Sciences"
author_affiliation: "George Mason University"
author_url: "http://exploringpossibilityspace.blogspot.com"
baseurl: ""
#baseurl: "http://tutorials.meritology.com"
url: "http://tutorials.meritology.com"

# Build settings
markdown: kramdown

exclude:
- node_modules