# Site settings
title: "Library"
gems:
  - jekyll-last-modified-at
collections:
  fundamentals:
    output: true
    sort_order: 0
    index : true
    title: "Tutorial: Fundamentals of Probabilistic Programming"
  riskmodels:
    output: true
    sort_order: 1
    index : true
    title: "Tutorial: Risk Modeling with Probabilistic Programming"
  financial:
    output: true
    sort_order: 2
    index : true
    title: "Tutorial: Financial Applications of Probabilistic Programming"
  institutions:
    output: true
    sort_order: 3
    index : true
    title: "Models of Teams, Institutions, and Innovation"
  other:
    output: true
    sort_order: 10
    index : false
    title: "Other"
author: "Russell Cameron Thomas"
author_title: "PhD Candidate"
author_dept: "Computational & Data Sciences"
author_affiliation: "George Mason University"
author_url: "http://exploringpossibilityspace.blogspot.com"
baseurl: ""
#baseurl: "http://tutorials.meritology.com"
url: "http://tutorials.meritology.com"

# Build settings
markdown: kramdown

exclude:
- node_modules