#!/bin/bash
set -e
set -x

npm install --save webppl@latest webppl-timeit@latest webppl-dp@latest agentmodels/webppl-agents mhtess/webppl-csv

cd node_modules/webppl
npm install
grunt bundle:../webppl-timeit:../webppl-dp:../webppl-agents:../webppl-csv
cp bundle/webppl.min.js ../../assets/js/webppl.min.js
cd ../..
echo "Success."
